let AttributesObject = {
  HP: 0,
  DamageBonus: 0,
  Build: 0,
  MovementRate: 0,
  Sanity: 0,
  Magic: 0,
  Luck: 0,
};

let CharacteristicsObject = {
  Strength: 0,
  Constitution: 0,
  Size: 0,
  Dexterity: 0,
  Appearance: 0,
  Education: 0,
  Intelligence: 0,
  Power: 0,
  Archeology: 0,
  Charm: 0,
  Climb: 0,
  CreditRating: 0,
  Dodge: 0,
  DriveAuto: 0,
  FightBrawl: 0,
  Handgun: 0,
  RifleShotgun: 0,
  FirstAid: 0,
  History: 0,
  Intimidate: 0,
  Jump: 0,
  Latin: 0,
  Greek: 0,
  Hieroglyphs: 0,
  English: 0,
  LibraryUse: 0,
  Listen: 0,
  MechRepair: 0,
  NaturalWorld: 0,
  Navigate: 0,
  Occult: 0,
  Persuade: 0,
  Psychology: 0,
  SleightOfHand: 0,
  SpotHidden: 0,
  Stealth: 0,
  Swim: 0,
  Throw: 0,
  Track: 0,
};
